#!/bin/sh

rofi \
-color-window "#1F1F1F,#1F1F1F,#1F1F1F" \
-color-normal "#1F1F1F,#FFFFFF,#1F1F1F,#1e88e5" \
-modi run \
-show drun \
-location 7 \
-theme-str "prompt { enabled:false; }" \
-yoffset -45 \
-xoffset 0 \
-line-padding 2 \
-columns 1 \
-width 25 \
-lines 25 \
-padding 10 \
-hide-scrollbar \
-show-icons \
-drun-icon-theme "Papirus" \
-font "Roboto 12"
