#!/bin/sh

MENU="$(rofi \
  -color-window '#1F1F1F,#1F1F1F,#1F1F1F' \
  -color-normal '#1F1F1F,#FFFFFF,#1F1F1F,#1e88e5' \
  -sep "|" \
  -dmenu -i -p 'Settings' \
  -location 7 \
  -yoffset -45 \
  -xoffset 5 \
  -width 15 \
  -hide-scrollbar \
  -line-padding  \
  -padding 10 \
  -lines 6 \
  -font "Roboto 12; Material Icons 12" \
  <<< ' Sound| Monitor| Network| Bluetooth| Power| All')"

case "$MENU" in
  *All) xfce4-settings-manager ;;
  *Sound) pavucontrol ;;
  *Monitor) arandr ;;
  *Network) nm-connection-editor ;;
  *Bluetooth) blueman-manager ;;
  *Power) xfce4-power-manager-settings
esac